GET http://localhost:3000/token HTTP/1.1
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGQ1MTlkMjA3NDE1OTdlNjEzZGM3ZCIsImlhdCI6MTcyMDUzNzU0MiwiZXhwIjoxNzIwNTM3NjYyfQ.d2jSjr6AuJkk6nvV-3O_YJSTLY7CyweZRoMYTJhFJ4k