GET http://localhost:3000/token HTTP/1.1
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGJjNTRjZDYyNTc4ZTdiYThiYmQ2ZSIsImlhdCI6MTcyMDQzNjA1OCwiZXhwIjoxNzIwNDM2MDg4fQ.4vjOi438Ke9yK8BF1kQGB6s22l0-cdibJ5jtH5kkcng