GET http://localhost:3000/token HTTP/1.1
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODUyMzY4MDAwMWE4N2UyOWI1MThjNSIsImlhdCI6MTcyMDAwMTM5OCwiZXhwIjoxNzIyNTkzMzk4fQ.zIFewytyH03WWeYX80NxgxrX_6ORmFS6bD7VUXV_5Ak


