POST http://localhost:3000/add-event HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2YxMGIwZTM1YTUxNjU2YzY1OTg4MyIsImlhdCI6MTcxOTYwMzM4MywiZXhwIjoxNzE5NjA5MzgzfQ.ka_4qHJNWNR8H2ecJXVVTxat4jLjqtjjevr67Wc83X8
Content-Type: application/json

{
    "title": "Pineta8",
    "description": "Posto bello",
    "location": "Catania",
    "date": "27/06/2024"
}