GET http://localhost:3000/token HTTP/1.1
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2M0ZTM0NmJjNGVlMjhmMWU2ZGEwNiIsImlhdCI6MTcxOTQyMjYyOSwiZXhwIjoxNzIyMDE0NjI5fQ.1fbEOngHhjJDa7KKb5dbhOgriviz2boP1k5thEsGMPM


