GET http://localhost:3000/token HTTP/1.1
Content-Type: application/json
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzJkOGI1N2U1NWVjYTdiN2UyYzlmNyIsImlhdCI6MTcxODgwMjYyMSwiZXhwIjoxNzE4ODAzODIxfQ.1sUkshCXfbSi-Mu13oMyV8v6tGv3xrqOfYdJmZCCR-A
