GET http://localhost:3000/token HTTP/1.1
Content-Type: application/json
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzNmNDMzNWFmZmY3NWM3NmI0OWFlNSIsImlhdCI6MTcxODg3NzM1MiwiZXhwIjoxNzIwMDg2OTUyfQ.zLCwt-gC9QONaZFe8EIjcqhRQ2wGw2g9eDiaRNtdG0o


