POST http://localhost:3000/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "saro@example.com",
    "password": "password123"
}

###

# access/ refresh(logic to add, later) token
# saro papa access token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmIyNDhmZGQwYWIzYjY2M2ZiOTE2MCIsImlhdCI6MTcxODI5OTAyN30.a7V93j7iguHLGl05_qm8IrtUDrk9HTnBuY7bM8_rmXE