GET http://localhost:3000/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzQwNmU2N2I0MjU4ZjFlNDg4ZjVkZiIsImlhdCI6MTcxOTMyOTU1NiwiZXhwIjoxNzE5MzI5NjE2fQ.3MRcdG3UMTkjOfhmLKCLFRt4k40eJ3EhWp_tTbryswQ

