GET http://localhost:3000/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzMxMjRjNTVhOGU4ZGVlNzIxNGQwMCIsImlhdCI6MTcxODgxODcyNiwiZXhwIjoxNzE4ODE4Nzg2fQ.ZLZxVzV8p1Koe_14KWQDMZYX2QKrfyw4pQNt6Cg98GI

