POST http://localhost:3000/add-event HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODJjMGYwZWVhZmExZDYyZjZlNzdiNCIsImlhdCI6MTcxOTg0OTI2MCwiZXhwIjoxNzI1ODQ5MjYwfQ.lg4B1PCV3Kb_ttDgIgiTMN64kdmpFyQCyjCJ0FYPtKc
Content-Type: application/json

{
    "title": "non lo so",
    "description": "Posto bello",
    "location": "Catania",
    "date": "02/07/2024"
}