POST http://localhost:3000/add-event HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODUyMzY4MDAwMWE4N2UyOWI1MThjNSIsImlhdCI6MTcyMDAxNDg4NCwiZXhwIjoxNzIwMDE1Nzg0fQ.EN6SMCwZYBVOwCE7OgfpCWufj8BpsCOuLeDE8B5fG7M
Content-Type: application/json

{
    "title": "un evento fantastico",
    "description": "Posto bello",
    "location": "Catania",
    "date": "04/07/2024"
}