PUT http://localhost:3000/update-event/6682c165eeafa1d62f6e77bc
Authorization: Bearere eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODJjMGYwZWVhZmExZDYyZjZlNzdiNCIsImlhdCI6MTcxOTg0NTExMSwiZXhwIjoxNzI1ODQ1MTExfQ.CjfiX6AlxF5Lkpfrup7LQ6NljPwrtthlMqGvhCaK7bI
Content-Type: application/json

{
    "title": "Pineta5",
    "description": "Posto molto beeeeeeeelllloooooo",
    "location": "Catania",
    "date": "07/07/2024"
}