POST http://localhost:3000/add-friend HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODQwZWYzZGY1MTRkYmZmNGZkZGIxZiIsImlhdCI6MTcxOTkzNzQwNSwiZXhwIjoxNzE5OTM4MzA1fQ.e0EHKZplED_Opc4aGOjile8kraMzdhREae_McL2T3fE
Content-Type: application/json

{
    "email": "melo@example.com"
}