GET http://localhost:3000/fetch-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGQxNDdmMjQyMTBhYTgyMWI5N2Q4MyIsImlhdCI6MTcyMDUyMTg2NywiZXhwIjoxNzIwNTIxOTI3fQ.v-Vm1G8d9W4S3CrBDzQACWwugiIaym2sAp7IK4iXuAM