GET http://localhost:3000/fetch-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODI4N2Q2YWVjOTkxZWFkMTAxMDZlZCIsImlhdCI6MTcxOTkzMzc1NCwiZXhwIjoxNzE5OTM0NjU0fQ.TCrr9-FzCOnmjJXY1H7STA50RVH5wl4qLqRKSAaUTgs