GET http://localhost:3000/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGMxOWE5OWU1OGY3NmY4YWYyYzM4OCIsImlhdCI6MTcyMDQ1ODU5NywiZXhwIjoxNzIwNDU4NjU3fQ.NTDYzzm52xkCePSVmziN0M-16k4BbvczeKos9hrcz3w