GET http://localhost:3000/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODI4N2Q2YWVjOTkxZWFkMTAxMDZlZCIsImlhdCI6MTcxOTkyNzg3NywiZXhwIjoxNzE5OTI4Nzc3fQ.xNExYa4T-jtzcVNpqNLv9Av2_UTBWua-AIbpNzSRIXQ