GET http://localhost:3000/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGJiODYyZGRlMTBiY2RkODU0Mzg2MyIsImlhdCI6MTcyMDQzNDk5NSwiZXhwIjoxNzIwNDM1ODk1fQ.Y1WC8PRS41OKKgzCV27KG2BEaWRKxkAxbcgraKEi87I